### ISSUE TITLE
[BUG] fail to reference resource in `resource.delivery.ocm.software`

### ISSUE THREAD

**Issue by reshnm** [open-component-model/ocm-k8s-toolkit#131]
**Describe the bug**

The controller fails to resolve a resource reference by `referencePath`:

```yaml
resource:
    byReference:
      resource:
        name: provider-image
      referencePath:
        - name: gardener-cluster-provider
```

This results in the following error message:

```
Warning  ReconcileArtifactFailed  0s    ocm-k8s-toolkit  resource not found in access spec
```

**To Reproduce**

`OCMRepository`:

```yaml
apiVersion: delivery.ocm.software/v1alpha1
kind: OCMRepository
metadata:
    namespace: default
    name: openmcp-repo
spec:
    repositorySpec:
        type: OCIRegistry
        baseUrl: ghcr.io/reshnm/openmcp
    interval: 5m
    suspend: false
    ocmConfig:
    - apiVersion: v1
      kind: Secret
      name: ocm-config
      namespace: default
      policy: Propagate
```

`Component`:

```yaml
apiVersion: delivery.ocm.software/v1alpha1
kind: Component
metadata:
  namespace: default
  name: openmcp-comp
spec:
  repositoryRef:
    namespace: default
    name: openmcp-repo
  component: github.com/openmcp-project/openmcp
  downgradePolicy: Deny
  semver: ">= v0.0.1"
  interval: 5m
  suspend: false
  ocmConfig:
    - apiVersion: v1
      kind: Secret
      name: ocm-config
      namespace: default
      policy: Propagate
```

`Resource`:

```yaml
apiVersion: delivery.ocm.software/v1alpha1
kind: Resource
metadata:
  namespace: default
  name: gardener-cluster-provider-image
spec:
  componentRef:
    name: openmcp-comp
  resource:
    byReference:
      resource:
        name: provider-image
      referencePath:
        - name: gardener-cluster-provider
  interval: 5m
  suspend: false
  ocmConfig:
    - apiVersion: v1
      kind: Secret
      name: ocm-config
      namespace: default
      policy: Propagate
```

`root` component:

```yaml
---
component:
  componentReferences:
  - componentName: github.com/openmcp-project/gardener-cluster-provider
    name: gardener-cluster-provider
    version: v0.1.0
  - componentName: github.com/openmcp-project/project-workspace-operator
    name: project-workspace-operators
    version: v0.1.0
  creationTime: "2025-02-26T09:41:38Z"
  name: github.com/openmcp-project/openmcp
  provider: openmcp.cloud
  repositoryContexts:
  - baseUrl: ghcr.io
    componentNameMapping: urlPath
    subPath: reshnm/openmcp
    type: OCIRegistry
  resources: []
  sources: []
  version: v0.1.0
meta:
  schemaVersion: v2
```

The `gardener-cluster-provider` sub-component:

```yaml
---
component:
  componentReferences: []
  creationTime: "2025-02-26T09:41:34Z"
  name: github.com/openmcp-project/gardener-cluster-provider
  provider: openmcp.cloud
  repositoryContexts:
  - baseUrl: ghcr.io
    componentNameMapping: urlPath
    subPath: reshnm/openmcp
    type: OCIRegistry
  resources:
  - access:
      imageReference: ghcr.io/reshnm/openmcp/github.com/openmcp-project/gardener-cluster-provider/images/provider-image:v0.1.0@sha256:c78ab13b81b567cf9df7508025be0500a967bb6154e2dd8e48ccabc8c6f7007f
      type: ociArtifact
    digest:
      hashAlgorithm: SHA-256
      normalisationAlgorithm: ociArtifactDigest/v1
      value: c78ab13b81b567cf9df7508025be0500a967bb6154e2dd8e48ccabc8c6f7007f
    name: provider-image
    relation: local
    type: ociImage
    version: v0.1.0
  sources: []
  version: v0.1.0
meta:
  schemaVersion: v2
```

The `Resource` should reference the `github.com/openmcp-project/openmcp` -> componentRef: `gardener-cluster-provider` -> resource: `provider-image`

The components and images on `ghcr.io` are public. Access credentials shouldn't be needed. 

**Expected behavior**

The resource should be able to be resolved.

**Screenshots**
N/A

**Desktop (please complete the following information):**

N/A

**Additional context**

Tested on head (and including the 051526ba4139d1472308d1e957c9864fd6c3f654 attempted fix)
