### ISSUE TITLE
Deployer Maturity: Deployer Managed Resource Deletion

### ISSUE THREAD

**Issue by frewilhelm** [open-component-model/ocm-k8s-toolkit#194]
**Description**

#172 introduces a basic implementation of a deployer using `kro`. In the meantime we decided to use the deployer as a generic applier for any Kubernetes resource (see #259). Accordingly, this issue is updated.

The new deployer will only `CreateOrUpdate` the passed Kubernetes OCM resources.

However, if the applied OCM resource is updated with the same Kubernetes resource but a different Kubernetes resource name, the current/applied resource must be deleted before the new one is applied.

Example:

OCM resource `k8s-resource` gets applied:

```yaml
apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: resource-1
spec:
  schema:
    apiVersion: v1alpha1
    kind: Simple
```

OCM resource `k8s-resource` gets updated:

```yaml
apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: resource-2
spec:
  schema:
    apiVersion: v1alpha1
    kind: Simple
```

If the OCM resource gets updated, the new resource `resource-2` would get applied. However, `resource-1` is still present in the cluster and would not get updated or deleted. Thus, `resource-1` just would get orphaned (depending on the object, it wouldn't really be orphaned, but since there would be no matching resource anymore, the lifecycle would be confusing and deployers might accumulate resources) and the `deployer` object would be (controller-) referenced by `resource-1` and `resource-2` which is not wanted as we aim to have a 1:1 relationship between any `deployer` and applied resource.

TODOs:
- [ ] Check if the `deployer` already has applied any resource by iterating through the resources and check for the owner-reference (probably, using an index would make sense)
  - [ ] If so, check if the name differs
    - [ ] If so, delete the initial applied resource
    - [ ] If not, update the initial applied resource
  - [ ] If not, create the resource

**Done Criteria**  
- [ ] Code has been reviewed by other team members
- [ ] Analysis of existing tests (Unit and Integration)
- [ ] Unit Tests created for new code or existing Unit Tests updated
- [ ] Integration Test Suite updated (includes deletion of existing unnecessary Integration Test and/or creation of new ones if required)
- [ ] Successful demonstration in Review
