### ISSUE TITLE
Explore how Kro handles CRD upgrades from their RGD and discuss possible versioning strategies for CRDs

### ISSUE THREAD

**Issue by frewilhelm** [open-component-model/ocm-k8s-toolkit#211]
**Description**

As the lifecycle of the CRDs created by a Kro RGD should be handled through Kro, we have to explore how Kro handles the CRD upgrade from CRDs created by a RGD and discuss with the Kro contributor how possible versioning strategies for these CRDs coud look like.

Consider a `ResourceGraphDefinition` that creates a CRD:

```yaml
apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: my-application
spec:
  schema:
    apiVersion: v1alpha1
    kind: Application
```

Now, this CRD gets an updated `apiVersion`, e.g. :

```yaml
apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: my-application
spec:
  schema:
    apiVersion: v1beta1 <<< Upgrade
    kind: Application
```

### Timebox: 1 day(s)

**Done Criteria**
The following questions must be answered:
- [x] Can there be the same CRD with several apiVersions in one Cluster?
- [ ] Should kro allow such an upgrade, if the v1alpha1 CRD is still present in the cluster?
- [ ] What (should) happens if the CRD is present and instances of that CRD are deployed?
- [ ] How will deployed instances of that CR be upgraded?

Optional:
- [ ] Do we have to implement some checks for the ocm.software `deployer` before upgrading a CRD
- [ ] How do we advise users that do not use the ocm.software `deployer` (creating the RGD directly) to upgrade such CRDs

Depending of the results of the above questions, these points must be done:
- [ ] Estimation of impact on existing code incl. tests
- [ ] Created refinable tasks for the actual implementation in #194
